# v1.6.1 0x0003 机器人血量数据

uint16 red_1_robot_hp
uint16 red_2_robot_hp
uint16 red_3_robot_hp
uint16 red_4_robot_hp
uint16 red_5_robot_hp
uint16 red_7_robot_hp
uint16 red_outpost_hp
uint16 red_base_hp

uint16 blue_1_robot_hp
uint16 blue_2_robot_hp
uint16 blue_3_robot_hp
uint16 blue_4_robot_hp
uint16 blue_5_robot_hp
uint16 blue_7_robot_hp
uint16 blue_outpost_hp
uint16 blue_base_hp

uint16 enemy_outpost_hp
uint16 outpost_hp
uint16 base_hp

bool team_color  # 队伍颜色 1->红 0->蓝
bool enemy_color